name: View Secrets

on:
  workflow_dispatch:

jobs:
  view-secrets:
    runs-on: ubuntu-latest
    
    steps:
      - name: Echo Database Secrets
        run: |
          echo "DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}"
          echo "DATABASE_HOST: ${{ secrets.DATABASE_HOST }}"
          echo "DATABASE_USER: ${{ secrets.DATABASE_USER }}"
          echo "DATABASE_NAME: ${{ secrets.DATABASE_NAME }}"
          
      - name: Echo R2 Secrets
        run: |
          echo "R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}"
          echo "R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}"
          echo "R2_ENDPOINT: ${{ secrets.R2_ENDPOINT }}"
          echo "R2_BUCKET_NAME: ${{ secrets.R2_BUCKET_NAME }}"